version: '3.8'

services:
  server:
    build: ./server
    container_name: server 
    ports:
      - "3001:3001"
    environment: 
      - mongodb+srv://srisowmyamannam:PTYPkMsp5AqqmGJC@cluster0.qmhhpzl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"